### ISSUE TITLE
Ошибка выполнения функций без параметров

### ISSUE THREAD

**Issue by ValentinKozlov** [DocHubTeam/DocHub#555]
У меня была функция:
```yaml
  get_ext_systems_pattern:
    title: Получает строку поиска в виде регулярного выражения для определения внешних систем
    code: >  
      (
        $ext_systems_pattern := /world\..*/;
      )
```
В новой версии dochub я получаю ошибку `"Cannot read properties of null (reading 'funcs')"`
После ввода фиктивного необязательного параметра функция работает.

```yaml
  get_ext_systems_pattern:
    title: Получает строку поиска в виде регулярного выражения для определения внешних систем
    # Вводим фиктивный параметр, так как в новой версии DocHub функции без параметров запрещены
    params:
      - alias: dummy_parameter
        required: false
    code: >  
      (
        $ext_systems_pattern := /world\..*/;
      )
```
