### ISSUE TITLE
Ошибка вывода контекста

### ISSUE THREAD

**Issue by ValentinKozlov** [DocHubTeam/DocHub#587]
Есть система с идентификатором:
```
components:
# L1 уровень
  b2b.sales_tools.product_45.aos:
    title: Система продажи
```
есть описание промежуточных доменов:
```
b2b.sales_tools:
    title: Стрим "Офлайн инструменты продаж"
    entity: stream  
  b2b.sales_tools.product_45:
    title: Продукт Продажи B2B
    entity: product
```
При выводе контекста:
```
contexts:
  aos.as_is:
    title: Общий контекст ПА-L1 со всеми связями
    location: Прикладной ландшафт ПА-L1/Офлайн инструменты продаж/Общий контекст
    extra-links: true    
```
контекст падает, если в промежуточном описании сделать кавычки: Стрим "Офлайн инструменты продаж"

Ошибка связана с тем, что при выводе региона некорреткно экранируются кавычки:
```
$Region(b2b.sales_tools,"[[/architect/components/b2b.sales_tools Стрим "Офлайн инструменты продаж"]]", ) {
```
