### ISSUE TITLE
После нажатия кнопки обновления в плагине слетает метамодель

### ISSUE THREAD

**Issue by villanella** [DocHubTeam/DocHub#599]
**Предусловия**
 IDEA UI + Windows или IDEA CE + Linux. В настройках IdeaPlugin 4.2.1 выбран режим Personal, Git server - None

1. Создать пустой проект в Idea
2. Создать dochub.yaml с таким содержанием:
```
docs:
  dochub.welcome:
    title: Start page
    location: Welcome
    source: welcome.md
    type: markdown
    description: Start page

imports:
  - test.md
```
3. Рядом в корне создать welcome.md:
```
# Start page

Description page
```
4. И test.md:
```
---
docs:
    dochub.test:
        title: Пример Markdown с включенным архитектурным манифестом
        type: markdown
        location: Test
        source: .
---
# Hello world!

Blah blah
```
5. Сохранить все
6. Нажать кнопку обновления в плагине

**Результат:**

Вместо главной страницы - ошибка:

![Image](https://github.com/user-attachments/assets/a174caf6-69ff-4cb8-bf10-39ba20a0bbe3)

Плагин не видит метамодель.

В меню доступны только Проблемы, Техрадар и JSONata.

В jsonata запросы docs и imports ничего не выдают.

В дебаггере ошибка - 

![Image](https://github.com/user-attachments/assets/423369ae-8485-49d3-b084-c43bfe03cb70)

Обходной путь - изменить любой символ в dochub.yaml и пересохранить - метамодель восстановится.
При последующем нажатии кнопки обновления - снова метамодель слетит.

P.S. Если выбрать в настройках Докхаба Personal+Gitlab+токен, то поведение аналогичное. Если Enterprise + DocHub server + токен, то ошибка "Корневой манифест dochub.yaml не найден", что тоже указывает на то, что плагин метамодель не видит.
